"""Versioned capture schemas and pure verifier construction findings.

No function in this package launches simulation/replay, attests production PASS,
accepts an episode, grants action authority, or writes quarantine state.
"""

from .checks import verify_episode
from .replay import compare_replay
from .types import (
    ActionChunkV1,
    ActionEvidenceRow,
    ActualGeometryV1,
    ActualSafetyRow,
    ChunkManifestV1,
    ConstructionFindings,
    ContractSourcesV1,
    EpisodeArtifactRoles,
    EpisodeProvenanceV1,
    EvidenceChunkRef,
    EvidenceReadLimits,
    EvidenceScope,
    FieldToleranceV1,
    MetricChunkV1,
    PerceptionRecoveryV1,
    PickPlaceTaskV1,
    PoseChannels,
    PoseGoal,
    ReachTaskV1,
    RecordedMetric,
    RecoveryLinkV1,
    ReplayToleranceProfileV1,
    RoleFinding,
    SafetyChannelsV1,
    SafetyChunkV1,
    SafetyIssuanceV1,
    SensorChunkV1,
    TerminationPayloadV1,
    TraceIndexRow,
    TrajectoryChunkV1,
    TrustedVerificationBinding,
    VerifierConfigurationV1,
)

__all__ = [
    "ActionChunkV1",
    "ActionEvidenceRow",
    "ActualGeometryV1",
    "ActualSafetyRow",
    "ChunkManifestV1",
    "ConstructionFindings",
    "ContractSourcesV1",
    "EpisodeArtifactRoles",
    "EpisodeProvenanceV1",
    "EvidenceChunkRef",
    "EvidenceReadLimits",
    "EvidenceScope",
    "FieldToleranceV1",
    "MetricChunkV1",
    "PerceptionRecoveryV1",
    "PickPlaceTaskV1",
    "PoseChannels",
    "PoseGoal",
    "ReachTaskV1",
    "RecordedMetric",
    "RecoveryLinkV1",
    "ReplayToleranceProfileV1",
    "RoleFinding",
    "SafetyChannelsV1",
    "SafetyChunkV1",
    "SafetyIssuanceV1",
    "SensorChunkV1",
    "TerminationPayloadV1",
    "TraceIndexRow",
    "TrajectoryChunkV1",
    "TrustedVerificationBinding",
    "VerifierConfigurationV1",
    "compare_replay",
    "verify_episode",
]
