import { expect, test } from "vitest";
import { nodeBadges, badgeParts } from "./runBadges";
import type { components } from "./api/schema";
import auditFixture from "./__fixtures__/run-audit.json";

// Generated by tests/test_v03_m6_run_inspectors.py from a real governed capability
// executed through CapabilityGateway, and byte-compared there on every pytest run.
const audit = auditFixture as Pick<
  components["schemas"]["RunAudit"],
  "schema_version" | "capability_results"
>;

test("indexes the audit's capability results by the node that issued them", () => {
  const badges = nodeBadges(audit);
  const results = audit.capability_results ?? [];
  expect(results.length).toBeGreaterThan(1);
  expect([...badges.keys()].sort()).toEqual(
    [...new Set(results.map((item) => item.request.node_id))].sort(),
  );
  for (const result of results) {
    const forNode = badges.get(result.request.node_id) ?? [];
    const badge = forNode.find((item) => item.requestId === result.request.request_id);
    expect(badge).toBeDefined();
    expect(badge!.capabilityId).toBe(result.request.capability_id);
    expect(badge!.status).toBe(result.status);
  }
});

test("carries the connector, connection, and binding the gateway really resolved", () => {
  const badges = nodeBadges(audit);
  const bound = (audit.capability_results ?? []).find((item) => item.connector_id);
  expect(bound, "the fixture must contain a connector-backed call").toBeDefined();
  const badge = (badges.get(bound!.request.node_id) ?? [])[0];
  expect(badge.connectorId).toBe(bound!.connector_id);
  expect(badge.connectionId).toBe(bound!.connection_id);
  expect(badge.bindingId).toBe(bound!.binding_id);
  expect(badgeParts(badge).map(([kind]) => kind)).toEqual([
    "connector",
    "connection",
    "binding",
  ]);
});

test("omits the identities the audit omits rather than inventing them", () => {
  const badges = nodeBadges(audit);
  const unbound = (audit.capability_results ?? []).find((item) => !item.connector_id);
  expect(unbound, "the fixture must contain an unbound call").toBeDefined();
  const badge = (badges.get(unbound!.request.node_id) ?? [])[0];
  expect(badge.connectorId).toBeUndefined();
  expect(badge.connectionId).toBeUndefined();
  expect(badge.bindingId).toBeUndefined();
  expect(badgeParts(badge)).toEqual([]);
});

test("an audit without capability results produces no badges at all", () => {
  expect(nodeBadges({ capability_results: [] }).size).toBe(0);
  expect(nodeBadges({}).size).toBe(0);
  expect(nodeBadges(undefined).size).toBe(0);
});

test("a repeated request identity is projected once", () => {
  const results = audit.capability_results ?? [];
  const doubled = nodeBadges({ capability_results: [...results, ...results] });
  const single = nodeBadges(audit);
  for (const [nodeId, badges] of doubled) {
    expect(badges.map((item) => item.requestId)).toEqual(
      (single.get(nodeId) ?? []).map((item) => item.requestId),
    );
  }
});

test("names the plugin behind a plugin-served call and no plugin for an OAuth one", () => {
  const badges = nodeBadges(audit);
  const results = audit.capability_results ?? [];
  const served = results.find((item) => item.connector_id?.startsWith("conndef_plugin_"));
  expect(served, "the fixture must contain a plugin-served call").toBeDefined();
  const badge = (badges.get(served!.request.node_id) ?? [])[0];
  // The plugin identity is the synthetic connector's suffix, minted by
  // `plugin_connector_id` in src/accretion/plugins/registration.py.
  expect(badge.pluginId).toBe(served!.connector_id!.slice("conndef_plugin_".length));
  expect(badgeParts(badge).map(([kind]) => kind)).toEqual(["plugin", "connector", "binding"]);

  const oauth = results.find(
    (item) => item.connector_id && !item.connector_id.startsWith("conndef_plugin_"),
  );
  expect(oauth, "the fixture must contain a non-plugin connector call").toBeDefined();
  const other = (badges.get(oauth!.request.node_id) ?? [])[0];
  expect(other.pluginId).toBeUndefined();
  expect(badgeParts(other).map(([kind]) => kind)).not.toContain("plugin");
});
