import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { McpServersPage } from "./McpServersPage";
import { authModeText, discoveredLabel, healthText, targetText } from "./mcpHealth";
import type { components } from "../api/schema";
import serversFixture from "./__fixtures__/mcp-servers.json";
import capabilitiesFixture from "./__fixtures__/mcp-capabilities.json";
import discoveryFixture from "./__fixtures__/mcp-discovery.json";

type McpServerDefinition = components["schemas"]["McpServerDefinition"];
type Capability = components["schemas"]["Capability"];
type McpDiscoverySnapshot = components["schemas"]["McpDiscoverySnapshot"];

// Generated by tests/test_v03_m6_admin_surface.py: the healthy server was really
// discovered against the in-process fake, and the broken one really had its circuit
// opened by M3's breaker. Byte-compared there, typed here.
const SERVERS = serversFixture as McpServerDefinition[];
const CAPABILITIES = capabilitiesFixture as Capability[];
const DISCOVERY = discoveryFixture as McpDiscoverySnapshot;

const HEALTHY = SERVERS.find((server) => server.connector_id === "research-openalex")!;
const BROKEN = SERVERS.find((server) => server.connector_id === "research-crossref")!;

function install(
  servers: McpServerDefinition[] = SERVERS,
  discovery: McpDiscoverySnapshot = DISCOVERY,
): string[] {
  const urls: string[] = [];
  vi.mocked(fetch).mockImplementation(async (input) => {
    const url = String(input);
    urls.push(url);
    const body = url.endsWith("/capabilities")
      ? CAPABILITIES
      : url.endsWith("/discovery")
        ? discovery
        : servers;
    return { ok: true, status: 200, json: async () => body } as Response;
  });
  return urls;
}

function renderPage() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={client}>
      <MemoryRouter initialEntries={["/admin/mcp"]}>
        <Routes><Route path="/admin/mcp" element={<McpServersPage />} /></Routes>
      </MemoryRouter>
    </QueryClientProvider>,
  );
}

vi.stubGlobal("fetch", vi.fn());

beforeEach(() => {
  vi.mocked(fetch).mockReset();
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

test("the page is headed MCP servers and the healthy and broken rows do not read alike", async () => {
  install();
  renderPage();

  expect(screen.getByRole("heading", { level: 1, name: "MCP servers" })).toBeInTheDocument();

  const healthy = within(await screen.findByRole("row", { name: HEALTHY.mcp_server_id }));
  expect(healthy.getByText("READY")).toBeInTheDocument();
  expect(healthy.getByText(healthText(HEALTHY))).toHaveTextContent("Healthy");
  expect(healthy.getByText("RESTRICTED")).toBeInTheDocument();
  expect(healthy.getByText(`HTTP · ${HEALTHY.endpoint}`)).toBeInTheDocument();

  const broken = within(await screen.findByRole("row", { name: BROKEN.mcp_server_id }));
  expect(broken.getByText("DEGRADED")).toBeInTheDocument();
  expect(broken.getByText(healthText(BROKEN))).toHaveTextContent("Circuit open until");
  expect(broken.getByText("3")).toBeInTheDocument();
  expect(healthy.queryByText("DEGRADED")).toBeNull();
});

test("two servers differing only in circuit_open_until are described differently", () => {
  // Same state, same failure count, same everything else: only the breaker differs, and
  // an operator must be able to tell "the breaker is open" from "it is not".
  const open = { ...BROKEN };
  const closed = { ...BROKEN, circuit_open_until: null };
  expect(open.state).toBe(closed.state);
  expect(open.consecutive_failures).toBe(closed.consecutive_failures);
  expect(healthText(open)).not.toBe(healthText(closed));
  expect(healthText(open)).toContain("Circuit open until");
  expect(healthText(closed)).toContain("Circuit closed");
});

test("a disabled server is described differently from a ready one", () => {
  const disabled: McpServerDefinition = { ...HEALTHY, enabled: false, state: "DISABLED" };
  expect(healthText(disabled)).not.toBe(healthText(HEALTHY));
  expect(healthText(disabled)).toContain("Disabled");
  expect(healthText(HEALTHY)).toContain("Healthy");
  // A server switched off must not be reported as merely never-checked: the two are
  // different diagnoses.
  expect(healthText(disabled)).not.toContain("Healthy");
});

test("the rendered rows change with the breaker, not just the derived helper", async () => {
  install([{ ...BROKEN, circuit_open_until: null }]);
  renderPage();

  const row = within(await screen.findByRole("row", { name: BROKEN.mcp_server_id }));
  expect(row.getByText(/Circuit closed, but 3 consecutive failures/)).toBeInTheDocument();
  expect(row.queryByText(/Circuit open until/)).toBeNull();
});

test("a stdio server reports its command where an HTTP server reports its endpoint", () => {
  const stdio: McpServerDefinition = {
    ...HEALTHY,
    transport: "STDIO",
    endpoint: null,
    command: ["uvx", "mcp-server-git"],
  };
  expect(targetText(stdio)).toBe("uvx mcp-server-git");
  expect(targetText(HEALTHY)).toBe(HEALTHY.endpoint);
});

test("inspecting a server shows its transport, patterns, capabilities, tools, and cache hints", async () => {
  const urls = install();
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${HEALTHY.name}` }));

  const panel = within(
    await screen.findByRole("region", { name: `MCP server detail ${HEALTHY.mcp_server_id}` }),
  );
  expect(panel.getByLabelText("Server target")).toHaveTextContent(
    `HTTP · ${HEALTHY.endpoint} · protocol 2026-07-28`,
  );
  expect(panel.getByLabelText("Tool patterns")).toHaveTextContent(
    "allow openalex_* · deny nothing",
  );

  const capabilities = within(await panel.findByLabelText("Server capabilities"));
  expect(
    capabilities.getByText("research.literature.search · MCP · enabled"),
  ).toBeInTheDocument();

  await waitFor(() =>
    expect(panel.getByLabelText("Discovery summary")).toHaveTextContent(
      "protocol 2026-07-28 · 5 tools · 0 resources · 0 resource templates · 0 prompts · schemas valid",
    ),
  );
  const tools = within(panel.getByLabelText("Discovered tools"));
  expect(tools.getByText("openalex_works_search")).toBeInTheDocument();
  expect(within(panel.getByLabelText("cache hint tools")).getByText(/300000 ms · PRIVATE/))
    .toBeInTheDocument();

  // SDD 16.3 asks for the discovered resources and prompts, not only the tools: this
  // server published neither, and the page has to say so rather than stay blank.
  expect(within(panel.getByLabelText("Discovered resources")).getByText(
    "This server published no resources.",
  )).toBeInTheDocument();
  expect(within(panel.getByLabelText("Discovered resource templates")).getByText(
    "This server published no resource templates.",
  )).toBeInTheDocument();
  expect(within(panel.getByLabelText("Discovered prompts")).getByText(
    "This server published no prompts.",
  )).toBeInTheDocument();

  expect(urls).toContain(`/api/v1/mcp/servers/${HEALTHY.mcp_server_id}/capabilities`);
  expect(urls).toContain(`/api/v1/mcp/servers/${HEALTHY.mcp_server_id}/discovery`);
});

test("the server listing is a focusable scroll region", async () => {
  install();
  renderPage();

  const region = await screen.findByRole("region", { name: "MCP servers" });
  expect(region).toHaveAttribute("tabindex", "-1");
  region.focus();
  expect(document.activeElement).toBe(region);
});

test("a server bound to an auth profile is described differently from an unauthenticated one", async () => {
  // SDD 16.3 requires the auth mode on the detail screen; the fixture server carries no
  // profile, so the differential pairs it with one that does.
  install([{ ...HEALTHY, auth_profile_ref: "authprof_openalex" }, BROKEN]);
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${HEALTHY.name}` }));
  const panel = within(
    await screen.findByRole("region", { name: `MCP server detail ${HEALTHY.mcp_server_id}` }),
  );
  expect(panel.getByLabelText("Auth mode")).toHaveTextContent("auth profile authprof_openalex");
  expect(authModeText(HEALTHY)).toContain("no auth profile");
  expect(authModeText({ ...HEALTHY, auth_profile_ref: "authprof_openalex" })).not.toBe(
    authModeText(HEALTHY),
  );
});

test("discovered resources, resource templates and prompts are listed, not just counted", async () => {
  const enriched: McpDiscoverySnapshot = {
    ...DISCOVERY,
    resources: [{ uri: "openalex://works", name: "works" }],
    resource_templates: [{ uriTemplate: "openalex://works/{id}" }],
    prompts: [{ name: "summarize_work" }],
  };
  install(SERVERS, enriched);
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${HEALTHY.name}` }));
  const panel = within(
    await screen.findByRole("region", { name: `MCP server detail ${HEALTHY.mcp_server_id}` }),
  );

  // `findByLabelText` would settle on the "no snapshot yet" paragraph, which carries the
  // same label, so wait on the content rather than on the element appearing.
  await waitFor(() =>
    expect(panel.getByLabelText("Discovery summary")).toHaveTextContent(
      "1 resources · 1 resource templates · 1 prompts",
    ),
  );
  // Each list must carry its own item: a page that rendered one list three times, or
  // rendered prompts under resources, fails here.
  const resources = within(panel.getByLabelText("Discovered resources"));
  expect(resources.getByText("works")).toBeInTheDocument();
  expect(resources.queryByText("summarize_work")).toBeNull();
  expect(
    within(panel.getByLabelText("Discovered resource templates")).getByText(
      "openalex://works/{id}",
    ),
  ).toBeInTheDocument();
  const prompts = within(panel.getByLabelText("Discovered prompts"));
  expect(prompts.getByText("summarize_work")).toBeInTheDocument();
  expect(prompts.queryByText("works")).toBeNull();
});

test("a discovered item with no name falls back to its uri and then to a stated unnamed case", () => {
  expect(discoveredLabel({ name: "a", uri: "b" })).toBe("a");
  expect(discoveredLabel({ uri: "b" })).toBe("b");
  expect(discoveredLabel({ uriTemplate: "c/{id}" })).toBe("c/{id}");
  expect(discoveredLabel({})).toBe("unnamed item");
});
