import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { PluginsPage } from "./PluginsPage";
import { pluginRows, providerProjections, resolutionText, scopeRequirements, scopeText } from "./pluginRows";
import type { components } from "../api/schema";
import pluginsFixture from "./__fixtures__/plugins.json";
import installationsFixture from "./__fixtures__/plugin-installations.json";
import detailFixture from "./__fixtures__/plugin-detail.json";

type MetaPlugin = components["schemas"]["MetaPlugin"];
type PluginInstallation = components["schemas"]["PluginInstallation"];
type PluginDetail = components["schemas"]["PluginDetail"];
type PluginConnectorResolution = components["schemas"]["PluginConnectorResolution"];

// Generated by tests/test_v03_m6_admin_surface.py from the live API and byte-compared
// there, so these are what /api/v1/plugins really answers rather than a guess. Typed
// against the generated schema, so a contract change breaks `npm run check` too.
const PLUGINS = pluginsFixture as MetaPlugin[];
const INSTALLATIONS = installationsFixture as PluginInstallation[];
const DETAIL = detailFixture as PluginDetail;

const RESEARCH = "accretion-research";
const SAMPLE = "accretion-sample-plugin";
const WORKSPACE = "wks_m6_01";

interface Call {
  url: string;
  method: string;
}

function install(): Call[] {
  const calls: Call[] = [];
  vi.mocked(fetch).mockImplementation(async (input, init) => {
    const url = String(input);
    calls.push({ url, method: init?.method ?? "GET" });
    const body = url.includes("/api/v1/plugins/installations")
      ? INSTALLATIONS
      : url.includes(`/api/v1/plugins/${RESEARCH}`)
        ? DETAIL
        : url.includes(`/api/v1/plugins/${SAMPLE}`)
          ? { ...DETAIL, plugin_id: SAMPLE, installation: null, recent_events: [] }
          : PLUGINS;
    return { ok: true, status: 200, json: async () => body } as Response;
  });
  return calls;
}

function renderPage() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={client}>
      <MemoryRouter initialEntries={["/admin/plugins"]}>
        <Routes><Route path="/admin/plugins" element={<PluginsPage />} /></Routes>
      </MemoryRouter>
    </QueryClientProvider>,
  );
}

vi.stubGlobal("fetch", vi.fn());

beforeEach(() => {
  vi.mocked(fetch).mockReset();
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

test("the page is headed Plugins and its two rows disagree on state, trust, and requested capabilities", async () => {
  install();
  renderPage();

  expect(screen.getByRole("heading", { level: 1, name: "Plugins" })).toBeInTheDocument();

  const research = within(await screen.findByRole("row", { name: RESEARCH }));
  expect(research.getByText("ENABLED")).toBeInTheDocument();
  expect(research.getByText("1.0.0")).toBeInTheDocument();
  expect(
    research.getByText(
      "research.literature.search · research.paper.fetch · research.metadata.resolve · research.citation.verify · github.search",
    ),
  ).toBeInTheDocument();

  // The differential: the second installed row shares the trust level but agrees on
  // nothing else, so a page that rendered one row's data twice fails here.
  const sample = within(await screen.findByRole("row", { name: SAMPLE }));
  expect(sample.getByText("DISABLED")).toBeInTheDocument();
  expect(sample.getByText("0.1.0")).toBeInTheDocument();
  expect(sample.getByText("accretion.sample.echo · accretion.sample.record")).toBeInTheDocument();
  expect(sample.queryByText("ENABLED")).toBeNull();
  expect(research.queryByText("DISABLED")).toBeNull();
});

test("a registry entry nobody installed is listed as not installed rather than omitted", async () => {
  install();
  renderPage();

  // `accretion-core-governance` is seeded into the registry and installed nowhere.
  const governance = within(await screen.findByRole("row", { name: "accretion-core-governance" }));
  expect(governance.getByText("NOT_INSTALLED")).toBeInTheDocument();
  expect(governance.getByText("none requested")).toBeInTheDocument();
});

test("inspecting a plugin reads its detail for the workspace it is installed in", async () => {
  const calls = install();
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${RESEARCH}` }));

  await waitFor(() =>
    expect(calls).toContainEqual({
      url: `/api/v1/plugins/${RESEARCH}?workspace_id=${WORKSPACE}`,
      method: "GET",
    }),
  );
  // A workspace-blind read would answer with no installation at all, so the query
  // string is load-bearing rather than decorative.
  expect(calls.map((call) => call.url)).not.toContain(`/api/v1/plugins/${RESEARCH}`);
});

test("the detail panel shows the version, state, grants, connector status, and lifecycle history", async () => {
  install();
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${RESEARCH}` }));

  const panel = within(await screen.findByRole("region", { name: `Plugin detail ${RESEARCH}` }));
  expect(panel.getByLabelText("Installation summary")).toHaveTextContent(
    "version 1.0.0 · state ENABLED · trust BUILTIN",
  );

  const requested = within(panel.getByLabelText("Requested capabilities"));
  expect(requested.getByText("research.literature.search")).toBeInTheDocument();
  expect(requested.getByText("github.search")).toBeInTheDocument();

  const grant = within(panel.getByLabelText("grant github.search"));
  expect(grant.getByText("GRANTED · requested github.read · granted github.read")).toBeInTheDocument();

  // Connector status is the diagnosis AC3-UI-01 asks for: optional-and-unsatisfied is
  // not the same fault as required-and-unsatisfied.
  const connector = within(panel.getByLabelText("connector research-openalex"));
  expect(connector.getByText("not satisfied — optional")).toBeInTheDocument();

  const events = within(panel.getByLabelText("Recent events"));
  expect(events.getByText("ENABLED · READY → ENABLED")).toBeInTheDocument();
  expect(events.getByText("INSTALL_VALIDATING · DISCOVERED → VALIDATING")).toBeInTheDocument();
});

test("connector status distinguishes satisfied, optional, and required-and-missing", () => {
  const base: PluginConnectorResolution = {
    connector_id: "research-openalex",
    required: false,
    satisfied: false,
    connection_id: null,
    missing_scopes: [],
  };
  expect(resolutionText(base)).toBe("not satisfied — optional");
  expect(resolutionText({ ...base, required: true })).toBe("not satisfied — required");
  expect(
    resolutionText({ ...base, required: true, missing_scopes: ["research.read"] }),
  ).toBe("not satisfied — required · missing scopes research.read");
  expect(resolutionText({ ...base, satisfied: true, connection_id: "conn_1" })).toBe(
    "satisfied by conn_1",
  );
});

test("the join keeps the installation's version and state, not the registry's", () => {
  const rows = new Map(pluginRows(PLUGINS, INSTALLATIONS).map((row) => [row.plugin_id, row]));
  const research = rows.get(RESEARCH);
  const registry = PLUGINS.find((entry) => entry.plugin_id === RESEARCH);
  const installation = INSTALLATIONS.find((item) => item.plugin_id === RESEARCH);
  expect(research?.state).toBe(installation?.state);
  expect(research?.version).toBe(installation?.version);
  expect(research?.registry).toBe(registry);
  expect(rows.get("accretion-core-governance")?.installation).toBeNull();
});

test("the listing is a focusable scroll region so it can be reached without a mouse", async () => {
  install();
  renderPage();

  const region = await screen.findByRole("region", { name: "Installed plugins" });
  // 0, not -1. This test is named for reaching the region WITHOUT A MOUSE, and -1 is
  // exactly what prevents that: it makes an element focusable only from script, and
  // removes it from the tab order. The assertion contradicted the test's own name until
  // axe-core 4.13's `scrollable-region-focusable` rule reported it on five routes -
  // `.registry-card` scrolls horizontally at narrow widths, so a keyboard user could see
  // the region and never reach its clipped content.
  expect(region).toHaveAttribute("tabindex", "0");
  region.focus();
  expect(document.activeElement).toBe(region);
});

test("the detail panel shows the manifest's skills, scopes, verifiers, policies and projections", async () => {
  install();
  renderPage();

  fireEvent.click(await screen.findByRole("button", { name: `Inspect ${RESEARCH}` }));
  const panel = within(await screen.findByRole("region", { name: `Plugin detail ${RESEARCH}` }));

  // SDD 16.1 lists all five on the detail screen. They live on the version record's
  // manifest, so a panel reading only the installation cannot show them.
  const skills = within(panel.getByLabelText("Skills"));
  expect(
    skills.getByLabelText("skill accretion-research-literature-review"),
  ).toBeInTheDocument();
  expect(skills.queryByLabelText("skill accretion-sample-echo")).toBeNull();

  const scopes = within(panel.getByLabelText("Required scopes"));
  expect(scopes.getByLabelText("scopes research-openalex")).toHaveTextContent(
    "optional · no scopes requested",
  );

  expect(within(panel.getByLabelText("Policies")).getByText("local-capability-policy"))
    .toBeInTheDocument();
  // The research manifest declares no verifiers and no projections, and an empty
  // section has to read as "none declared" rather than as a missing screen.
  expect(within(panel.getByLabelText("Verifiers")).getByText("This plugin declares no verifiers."))
    .toBeInTheDocument();
  expect(
    within(panel.getByLabelText("Provider projections")).getByText(
      "This plugin ships no provider projections.",
    ),
  ).toBeInTheDocument();
});

test("a required connector's scopes read differently from an optional connector's silence", () => {
  const manifest = DETAIL.version_record!.manifest;
  const withRequired = {
    ...manifest,
    required_connectors: [
      { connector_id: "github", scopes: ["repo:read", "issues:read"], reason: "" },
    ],
  };
  const requirements = scopeRequirements(withRequired);
  const optional = scopeRequirements(manifest);

  expect(requirements[0]).toEqual({
    connector_id: "github",
    required: true,
    scopes: ["repo:read", "issues:read"],
  });
  expect(scopeText(requirements[0])).toBe("required · scopes repo:read issues:read");
  expect(scopeText(optional[0])).toBe("optional · no scopes requested");
  expect(scopeText(requirements[0])).not.toBe(scopeText(optional[0]));
  expect(scopeRequirements(null)).toEqual([]);
});

test("provider projections are listed as provider-to-path pairs in a stable order", () => {
  const manifest = DETAIL.version_record!.manifest;
  expect(providerProjections(manifest)).toEqual([]);
  expect(
    providerProjections({
      ...manifest,
      provider_projections: { openai: "projections/openai.json", anthropic: "projections/a.json" },
    }),
  ).toEqual([
    ["anthropic", "projections/a.json"],
    ["openai", "projections/openai.json"],
  ]);
});
