FROM python@sha256:423ed6ab25b1921a477529254bfeeabf5855151dc2c3141699a1bfc852199fbf
COPY --chmod=0555 simulation-worker /opt/accretion/bin/simulation-worker
COPY --chmod=0555 accretion /opt/probe/accretion
LABEL dev.draveniq.accretion.scope="NONROBOT_CONSTRUCTION_PROBE"
