"""v0.5 canonical simulation contracts; runtime enforcement lives outside this package."""

from .envelopes import CanonicalWriterEnvelope
from .models import (
    CONTRACT_INVENTORY,
    CORE_CONTRACT_INVENTORY,
    SIMULATION_CAPABILITIES,
    ActionIntent,
    AdapterConformanceReport,
    EmbodiedVerificationResult,
    EmbodiedVerificationSpec,
    EmbodimentDescriptor,
    EpisodeQuarantineRecord,
    EpisodeRecord,
    ObservationSpec,
    PreflightCheck,
    PreparedCommand,
    RobotAdapterManifest,
    SafetyDecisionPayload,
    SafetyDecisionReceipt,
    SafetyEnvelope,
    SimulationActionReceipt,
    SimulationApprovalMatrix,
    SimulationDomainEvent,
    SimulationEnvironmentSnapshot,
    SimulationEpisodeApproval,
    SimulationExperimentContract,
    SimulationLease,
    SimulationPreflightReceipt,
    SimulationRunBinding,
)
from .signatures import (
    SAFETY_SIGNATURE_DOMAIN,
    TrustedSafetyKey,
    safety_signing_bytes,
    sign_safety_payload,
    verify_safety_signature,
)

__all__ = [
    "CONTRACT_INVENTORY",
    "CORE_CONTRACT_INVENTORY",
    "SIMULATION_CAPABILITIES",
    "ActionIntent",
    "AdapterConformanceReport",
    "CanonicalWriterEnvelope",
    "EmbodiedVerificationResult",
    "EmbodiedVerificationSpec",
    "EmbodimentDescriptor",
    "EpisodeQuarantineRecord",
    "EpisodeRecord",
    "ObservationSpec",
    "PreflightCheck",
    "PreparedCommand",
    "RobotAdapterManifest",
    "SafetyDecisionPayload",
    "SafetyDecisionReceipt",
    "SafetyEnvelope",
    "SimulationActionReceipt",
    "SimulationApprovalMatrix",
    "SimulationDomainEvent",
    "SimulationEnvironmentSnapshot",
    "SimulationEpisodeApproval",
    "SimulationExperimentContract",
    "SimulationLease",
    "SimulationPreflightReceipt",
    "SimulationRunBinding",
    "SAFETY_SIGNATURE_DOMAIN",
    "TrustedSafetyKey",
    "safety_signing_bytes",
    "sign_safety_payload",
    "verify_safety_signature",
]
