/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run */
        post: operations["pause_run_api_v1_runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runtimes */
        get: operations["list_runtimes_api_v1_runtimes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Health */
        get: operations["runtime_health_api_v1_runtimes__runtime_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/planning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Planning */
        get: operations["get_task_planning_api_v1_tasks__task_id__planning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_tasks__task_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/strategy-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Strategy Override */
        post: operations["create_strategy_override_api_v1_tasks__task_id__strategy_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactRef */
        ArtifactRef: {
            /** Artifact Id */
            artifact_id: string;
            /** Kind */
            kind: string;
            /**
             * Path
             * Format: path
             */
            path: string;
            /** Run Id */
            run_id: string;
            /** Sha256 */
            sha256?: string | null;
        };
        /**
         * AuthMode
         * @enum {string}
         */
        AuthMode: "SUBSCRIPTION" | "API" | "LOCAL";
        /** ContextBundle */
        ContextBundle: {
            /** Artifact Refs */
            artifact_refs?: string[];
            /** Constraints */
            constraints?: string[];
            /** Context Bundle Id */
            context_bundle_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Experience Refs */
            experience_refs?: string[];
            /** Freshness */
            freshness?: {
                [key: string]: unknown;
            };
            /** Permissions */
            permissions?: string[];
            /**
             * Phase
             * @default TASK_EXECUTION
             */
            phase: string;
            /** Previous Failure Refs */
            previous_failure_refs?: string[];
            /** Project Summary */
            project_summary: string;
            /** Provenance */
            provenance?: string[];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Task Ref */
            task_ref: string;
            /**
             * Token Budget
             * @default 8000
             */
            token_budget: number;
            /**
             * Version
             * @default context-bundle-v1
             * @constant
             */
            version: "context-bundle-v1";
            /** Workspace Map */
            workspace_map?: {
                [key: string]: unknown;
            };
        };
        /** ErrorSummary */
        ErrorSummary: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "DIRECT" | "LOOP" | "GRAPH" | "HYBRID";
        /**
         * ExpectedHorizon
         * @enum {string}
         */
        ExpectedHorizon: "SHORT" | "MEDIUM" | "LONG";
        /** FeatureEvidence */
        FeatureEvidence: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Feature */
            feature: string;
            /** Rationale */
            rationale: string;
            /** Source */
            source: string;
            /** Value */
            value?: boolean | number | string | string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OverridePolicyResult
         * @enum {string}
         */
        OverridePolicyResult: "ACCEPTED" | "DENIED_TEMPLATE_MISMATCH" | "DENIED_SAFETY_POLICY";
        /** Project */
        Project: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
            /**
             * Repository Path
             * Format: path
             */
            repository_path: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Repository Path
             * Format: path
             */
            repository_path: string;
        };
        /** PromptContract */
        PromptContract: {
            /** Completion Criteria */
            completion_criteria?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Examples */
            examples?: {
                [key: string]: unknown;
            }[];
            /** Hard Constraints */
            hard_constraints?: string[];
            /** Non Goals */
            non_goals?: string[];
            /** Objective */
            objective: string;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            };
            /** Prompt Contract Id */
            prompt_contract_id: string;
            /** Role */
            role: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Task Id */
            task_id: string;
            /** Tool Rules */
            tool_rules?: string[];
            /** Uncertainty Policy */
            uncertainty_policy?: {
                [key: string]: unknown;
            };
            /**
             * Version
             * @default p1-task-execution-v1
             * @constant
             */
            version: "p1-task-execution-v1";
        };
        /**
         * Provider
         * @enum {string}
         */
        Provider: "CLAUDE" | "CODEX" | "FAKE" | "DETERMINISTIC" | "HUMAN";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** Run */
        Run: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            error?: components["schemas"]["ErrorSummary"] | null;
            /**
             * Last Sequence
             * @default 0
             */
            last_sequence: number;
            /** Project Id */
            project_id: string;
            provider: components["schemas"]["Provider"];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id?: string | null;
            state: components["schemas"]["RunState"];
            /** Task Id */
            task_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Workspace Lease Id */
            workspace_lease_id?: string | null;
        };
        /** RunCreate */
        RunCreate: {
            /** @default FAKE */
            provider: components["schemas"]["Provider"];
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "PENDING" | "STARTING" | "RUNNING" | "PAUSED" | "RECONCILING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "REQUIRES_HUMAN";
        /** RuntimeHealth */
        RuntimeHealth: {
            /**
             * Active Runs
             * @default 0
             */
            active_runs: number;
            /**
             * Active Sessions
             * @default 0
             */
            active_sessions: number;
            auth_mode: components["schemas"]["AuthMode"];
            /** Capabilities */
            capabilities?: string[];
            last_error?: components["schemas"]["ErrorSummary"] | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at?: string;
            /** @default UNKNOWN */
            observed_usage_pressure: components["schemas"]["UsagePressure"];
            provider: components["schemas"]["Provider"];
            /** Runtime Id */
            runtime_id: string;
            /** Runtime Version */
            runtime_version: string;
            status: components["schemas"]["RuntimeStatus"];
        };
        /**
         * RuntimeStatus
         * @enum {string}
         */
        RuntimeStatus: "READY" | "BUSY" | "RATE_LIMITED" | "AUTH_REQUIRED" | "UNAVAILABLE" | "DEGRADED";
        /** StrategyDecision */
        StrategyDecision: {
            /** Alternatives */
            alternatives?: components["schemas"]["ExecutionMode"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Decision Id */
            decision_id: string;
            /** Matched Rules */
            matched_rules?: string[];
            /** Operator Override Allowed */
            operator_override_allowed: boolean;
            /**
             * Policy Version
             * @default selector-v1
             * @constant
             */
            policy_version: "selector-v1";
            /** Rationale */
            rationale: string;
            /**
             * Requires Approval
             * @default false
             */
            requires_approval: boolean;
            /**
             * Requires Independent Verifier
             * @default false
             */
            requires_independent_verifier: boolean;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            selected_mode: components["schemas"]["ExecutionMode"];
            /** Selected Template Id */
            selected_template_id: string;
            /** Supersedes Decision Id */
            supersedes_decision_id?: string | null;
            /** Task Id */
            task_id: string;
            /** Task Profile Ref */
            task_profile_ref: string;
        };
        /** StrategyOverride */
        StrategyOverride: {
            /** Accepted */
            accepted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Denial Reason */
            denial_reason?: string | null;
            /** Operator Identity */
            operator_identity: string;
            /** Original Decision Id */
            original_decision_id: string;
            /** Override Id */
            override_id: string;
            policy_result: components["schemas"]["OverridePolicyResult"];
            /** Reason */
            reason: string;
            requested_mode: components["schemas"]["ExecutionMode"];
            /** Requested Template Id */
            requested_template_id: string;
            /** Resulting Decision Id */
            resulting_decision_id?: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Task Id */
            task_id: string;
        };
        /** StrategyOverrideCreate */
        StrategyOverrideCreate: {
            /** Reason */
            reason: string;
            requested_mode: components["schemas"]["ExecutionMode"];
            /** Requested Template Id */
            requested_template_id: string;
        };
        /** StrategyOverrideResult */
        StrategyOverrideResult: {
            current_decision: components["schemas"]["StrategyDecision"];
            override: components["schemas"]["StrategyOverride"];
        };
        /** Task */
        Task: {
            /** Context Bundle Id */
            context_bundle_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Current Profile Id */
            current_profile_id?: string | null;
            /** Current Strategy Decision Id */
            current_strategy_decision_id?: string | null;
            envelope: components["schemas"]["TaskEnvelope"];
            /** Prompt Contract Id */
            prompt_contract_id?: string | null;
        };
        /** TaskBudgets */
        TaskBudgets: {
            /**
             * Max Loop Iterations
             * @default 1
             */
            max_loop_iterations: number;
            /**
             * Max Parallel Runs
             * @default 1
             */
            max_parallel_runs: number;
            /**
             * Max Turns
             * @default 20
             */
            max_turns: number;
            /**
             * Wall Time Seconds
             * @default 1800
             */
            wall_time_seconds: number;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Allowed Capabilities */
            allowed_capabilities?: string[];
            budgets?: components["schemas"]["TaskBudgets"];
            /** Constraints */
            constraints?: string[];
            /** Denied Capabilities */
            denied_capabilities?: string[];
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            }[];
            /** Objective */
            objective: string;
            /** Project Id */
            project_id: string;
            /** Requested Skills */
            requested_skills?: string[];
            /** Required Outputs */
            required_outputs?: {
                [key: string]: unknown;
            }[];
            /** @default LOW */
            risk_level: components["schemas"]["RiskLevel"];
            /** Success Criteria */
            success_criteria?: string[];
            /** @default OTHER */
            task_type: components["schemas"]["TaskType"];
        };
        /** TaskEnvelope */
        TaskEnvelope: {
            /** Allowed Capabilities */
            allowed_capabilities?: string[];
            budgets?: components["schemas"]["TaskBudgets"];
            /** Constraints */
            constraints?: string[];
            /**
             * Context Policy Ref
             * @default p0-local-worktree-v1
             */
            context_policy_ref: string;
            /** Denied Capabilities */
            denied_capabilities?: string[];
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            }[];
            /** Objective */
            objective: string;
            /** Project Id */
            project_id: string;
            /**
             * Prompt Contract Ref
             * @default p0-runtime-v1
             */
            prompt_contract_ref: string;
            /** Requested Skills */
            requested_skills?: string[];
            /** Required Outputs */
            required_outputs?: {
                [key: string]: unknown;
            }[];
            /** @default LOW */
            risk_level: components["schemas"]["RiskLevel"];
            /** Success Criteria */
            success_criteria?: string[];
            /** Task Id */
            task_id: string;
            /** @default OTHER */
            task_type: components["schemas"]["TaskType"];
            /**
             * Verifier Policy Ref
             * @default p0-observe-only-v1
             */
            verifier_policy_ref: string;
        };
        /** TaskPlanning */
        TaskPlanning: {
            context_bundle: components["schemas"]["ContextBundle"];
            current_decision: components["schemas"]["StrategyDecision"];
            current_profile: components["schemas"]["TaskProfile"];
            /** Decision History */
            decision_history?: components["schemas"]["StrategyDecision"][];
            /** Override History */
            override_history?: components["schemas"]["StrategyOverride"][];
            /** Profile History */
            profile_history?: components["schemas"]["TaskProfile"][];
            prompt_contract: components["schemas"]["PromptContract"];
            /** Task Id */
            task_id: string;
        };
        /** TaskProfile */
        TaskProfile: {
            /** Complexity */
            complexity?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Dependency Complexity */
            dependency_complexity?: number | null;
            expected_horizon: components["schemas"]["ExpectedHorizon"];
            /** Feedback Dependency */
            feedback_dependency?: number | null;
            /** Irreversible Actions */
            irreversible_actions: boolean;
            /** Observed Features */
            observed_features?: components["schemas"]["FeatureEvidence"][];
            /** Parallelism Potential */
            parallelism_potential?: number | null;
            /** Profile Confidence */
            profile_confidence: number;
            /** Profile Id */
            profile_id: string;
            /**
             * Profiler Version
             * @default deterministic-profiler-v1
             * @constant
             */
            profiler_version: "deterministic-profiler-v1";
            risk: components["schemas"]["RiskLevel"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Semantic Rationale */
            semantic_rationale: string;
            /** Structure Certainty */
            structure_certainty?: number | null;
            /** Task Id */
            task_id: string;
            /** Uncertainty */
            uncertainty?: number | null;
            /** Unknown Features */
            unknown_features?: string[];
            /** Verifier Strength */
            verifier_strength?: number | null;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "RESEARCH" | "ANALYSIS" | "IMPLEMENT" | "REVIEW" | "EXPERIMENT" | "OTHER";
        /**
         * UsagePressure
         * @enum {string}
         */
        UsagePressure: "UNKNOWN" | "LOW" | "MEDIUM" | "HIGH" | "EXHAUSTED";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_api_v1_runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runtimes_api_v1_runtimes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeHealth"][];
                };
            };
        };
    };
    runtime_health_api_v1_runtimes__runtime_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeHealth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_planning_api_v1_tasks__task_id__planning_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPlanning"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_tasks__task_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_strategy_override_api_v1_tasks__task_id__strategy_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyOverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOverrideResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
