"""Read the v0.4 locked test set once and print the tables ``results.md`` quotes.

This is the command that produced the numbers in
[`docs/research/v0.4/results.md`](../docs/research/v0.4/results.md). It is deliberately thin:
every refusal, every statistic and every table lives in
:mod:`accretion.routing.locked_test`, so the page can be regenerated by a test that never
shells out and the command cannot grow a number of its own.

Running it **is** a read of the locked test set. It appends a row to
``docs/research/v0.4/access-log.jsonl`` naming the principal, the pre-registration digest, the
timestamp and the reason, and that row is committed. The read is refused unless the
pre-registration on disk still hashes to the digest the corpus pinned and
``ACCRETION_ROUTER_LOCKED_TEST=1`` is set::

    ACCRETION_ROUTER_LOCKED_TEST=1 PYTHONPATH=src uv run --no-sync python \\
      scripts/router_locked_test.py --principal usr-release-v0.4 \\
      --reason "the v0.4.0 release's locked read"

``--corpus`` selects which of the two corpora the tables are *keyed* on; both are read either
way, because the drift holdout is reported beside the locked result and a page that could quote
one without the other would make the holdout optional. ``--access-log`` exists for a rehearsal
that must not touch the committed log, and says so in its help text rather than hiding behind a
default.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:  # pragma: no cover - import bootstrap
    sys.path.insert(0, str(ROOT / "src"))

from accretion.routing.baselines import BASELINE_ORDER  # noqa: E402
from accretion.routing.locked_test import (  # noqa: E402
    ABLATION_IDS,
    ACCESS_LOG_PATH,
    DRIFT_CORPUS_ROOT,
    LOCKED_CORPUS_ROOT,
    LockedTestRead,
    LockedTestRefused,
    LockedTestRunner,
    read_access_log,
    render_blocks,
)
from accretion.routing.split import SplitViolation  # noqa: E402

CORPUS_ROOTS = {"locked": LOCKED_CORPUS_ROOT, "drift": DRIFT_CORPUS_ROOT}


def build_parser() -> argparse.ArgumentParser:
    """The command line. Every argument is required to be said out loud except the log path."""

    parser = argparse.ArgumentParser(
        prog="router_locked_test",
        description="Read the v0.4 locked test set once and print the release's tables.",
    )
    parser.add_argument(
        "--corpus",
        choices=sorted(CORPUS_ROOTS),
        default="locked",
        help="which corpus the report is keyed on; both are read (default: locked)",
    )
    parser.add_argument(
        "--principal",
        required=True,
        help="who is reading the locked test set; recorded in the access log",
    )
    parser.add_argument(
        "--reason",
        required=True,
        help="why the locked test set is being read; recorded in the access log",
    )
    parser.add_argument(
        "--access-log",
        type=Path,
        default=ACCESS_LOG_PATH,
        help=(
            "where the access rows are appended; point this outside the repository for a "
            f"rehearsal that must not touch the committed log (default: {ACCESS_LOG_PATH})"
        ),
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the blocks as one JSON document instead of printing them",
    )
    return parser


def read(
    corpus_root: Path, *, principal: str, reason: str, access_log: Path, accessed_at: datetime
) -> LockedTestRead:
    """One released read of one corpus: every §8.1 comparator plus the ten §14 ablations."""

    runner = LockedTestRunner(corpus_root, access_log_path=access_log)
    return runner.run(
        list(BASELINE_ORDER),
        principal=principal,
        reason=reason,
        accessed_at=accessed_at,
        ablation_ids=ABLATION_IDS,
    )


def main(argv: list[str] | None = None) -> int:
    """Read both corpora, render the blocks, and print them. Returns 2 on any refusal."""

    args = build_parser().parse_args(argv)
    accessed_at = datetime.now(UTC)
    try:
        reads = {
            name: read(
                root,
                principal=args.principal,
                reason=f"{args.reason} ({name} corpus)",
                access_log=args.access_log,
                accessed_at=accessed_at,
            )
            for name, root in sorted(CORPUS_ROOTS.items())
        }
    except (LockedTestRefused, SplitViolation) as error:
        print(f"the locked test set was not read: {error}", file=sys.stderr)
        return 2

    blocks = render_blocks(reads["locked"], reads["drift"])
    if args.json:
        print(
            json.dumps(
                {
                    "keyed_on": args.corpus,
                    "access_log": str(args.access_log),
                    "access_log_rows": len(read_access_log(args.access_log)),
                    "blocks": blocks,
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0

    print(f"locked test read - keyed on the {args.corpus} corpus")
    print(f"access log {args.access_log} now holds {len(read_access_log(args.access_log))} rows")
    for block in blocks.values():
        print()
        print(block)
    return 0


if __name__ == "__main__":  # pragma: no cover - a maintenance entry point, not a test path
    raise SystemExit(main())
